version: '3.7'

services:
  node1:
    image: firrsdocker/hotstuff:2
    volumes:
      - ./:/home/hotstuff/distributedHotstuff
    user: "hotstuff"
    working_dir: /home/hotstuff/distributedHotstuff
    networks:
      - HotStuff
    command: [ "./hotstuff", "-id", "1" ]

  node2:
    image: firrsdocker/hotstuff:2
    volumes:
      - ./:/home/hotstuff/distributedHotstuff
    user: "hotstuff"
    working_dir: /home/hotstuff/distributedHotstuff
    networks:
      - HotStuff
    command: [ "./hotstuff", "-id", "2" ]

  node3:
    image: firrsdocker/hotstuff:2
    volumes:
      - ./:/home/hotstuff/distributedHotstuff
    user: "hotstuff"
    working_dir: /home/hotstuff/distributedHotstuff
    networks:
      - HotStuff
    command: [ "./hotstuff", "-id", "3" ]

  node4:
    image: firrsdocker/hotstuff:2
    volumes:
      - ./:/home/hotstuff/distributedHotstuff
    user: "hotstuff"
    working_dir: /home/hotstuff/distributedHotstuff
    networks:
      - HotStuff
    command: [ "./hotstuff", "-id", "4" ]

  node5:
    image: firrsdocker/hotstuff:2
    volumes:
      - ./:/home/hotstuff/distributedHotstuff
    user: "hotstuff"
    working_dir: /home/hotstuff/distributedHotstuff
    networks:
      - HotStuff
    command: [ "./hotstuff", "-id", "5" ]

  node6:
    image: firrsdocker/hotstuff:2
    volumes:
      - ./:/home/hotstuff/distributedHotstuff
    user: "hotstuff"
    working_dir: /home/hotstuff/distributedHotstuff
    networks:
      - HotStuff
    command: [ "./hotstuff", "-id", "6" ]

  node7:
    image: firrsdocker/hotstuff:2
    volumes:
      - ./:/home/hotstuff/distributedHotstuff
    user: "hotstuff"
    working_dir: /home/hotstuff/distributedHotstuff
    networks:
      - HotStuff
    command: [ "./hotstuff", "-id", "7" ]

  node8:
    image: firrsdocker/hotstuff:2
    volumes:
      - ./:/home/hotstuff/distributedHotstuff
    user: "hotstuff"
    working_dir: /home/hotstuff/distributedHotstuff
    networks:
      - HotStuff
    command: [ "./hotstuff", "-id", "8" ]

  node9:
    image: firrsdocker/hotstuff:2
    volumes:
      - ./:/home/hotstuff/distributedHotstuff
    user: "hotstuff"
    working_dir: /home/hotstuff/distributedHotstuff
    networks:
      - HotStuff
    command: [ "./hotstuff", "-id", "9" ]

  node10:
    image: firrsdocker/hotstuff:2
    volumes:
      - ./:/home/hotstuff/distributedHotstuff
    user: "hotstuff"
    working_dir: /home/hotstuff/distributedHotstuff
    networks:
      - HotStuff
    command: [ "./hotstuff", "-id", "10" ]

  node11:
    image: firrsdocker/hotstuff:2
    volumes:
      - ./:/home/hotstuff/distributedHotstuff
    user: "hotstuff"
    working_dir: /home/hotstuff/distributedHotstuff
    networks:
      - HotStuff
    command: [ "./hotstuff", "-id", "11" ]

  node12:
    image: firrsdocker/hotstuff:2
    volumes:
      - ./:/home/hotstuff/distributedHotstuff
    user: "hotstuff"
    working_dir: /home/hotstuff/distributedHotstuff
    networks:
      - HotStuff
    command: [ "./hotstuff", "-id", "12" ]

  node13:
    image: firrsdocker/hotstuff:2
    volumes:
      - ./:/home/hotstuff/distributedHotstuff
    user: "hotstuff"
    working_dir: /home/hotstuff/distributedHotstuff
    networks:
      - HotStuff
    command: [ "./hotstuff", "-id", "13" ]

  node14:
    image: firrsdocker/hotstuff:2
    volumes:
      - ./:/home/hotstuff/distributedHotstuff
    user: "hotstuff"
    working_dir: /home/hotstuff/distributedHotstuff
    networks:
      - HotStuff
    command: [ "./hotstuff", "-id", "14" ]

  node15:
    image: firrsdocker/hotstuff:2
    volumes:
      - ./:/home/hotstuff/distributedHotstuff
    user: "hotstuff"
    working_dir: /home/hotstuff/distributedHotstuff
    networks:
      - HotStuff
    command: [ "./hotstuff", "-id", "15" ]

  node16:
    image: firrsdocker/hotstuff:2
    volumes:
      - ./:/home/hotstuff/distributedHotstuff
    user: "hotstuff"
    working_dir: /home/hotstuff/distributedHotstuff
    networks:
      - HotStuff
    command: [ "./hotstuff", "-id", "16" ]

  node17:
    image: firrsdocker/hotstuff:2
    volumes:
      - ./:/home/hotstuff/distributedHotstuff
    user: "hotstuff"
    working_dir: /home/hotstuff/distributedHotstuff
    networks:
      - HotStuff
    command: [ "./hotstuff", "-id", "17" ]

  node18:
    image: firrsdocker/hotstuff:2
    volumes:
      - ./:/home/hotstuff/distributedHotstuff
    user: "hotstuff"
    working_dir: /home/hotstuff/distributedHotstuff
    networks:
      - HotStuff
    command: [ "./hotstuff", "-id", "18" ]

  node19:
    image: firrsdocker/hotstuff:2
    volumes:
      - ./:/home/hotstuff/distributedHotstuff
    user: "hotstuff"
    working_dir: /home/hotstuff/distributedHotstuff
    networks:
      - HotStuff
    command: [ "./hotstuff", "-id", "19" ]

  node20:
    image: firrsdocker/hotstuff:2
    volumes:
      - ./:/home/hotstuff/distributedHotstuff
    user: "hotstuff"
    working_dir: /home/hotstuff/distributedHotstuff
    networks:
      - HotStuff
    command: [ "./hotstuff", "-id", "20" ]


networks:
  HotStuff:
    external: true
