version: '3.7'

services:
  node1:
    image: hotstuff:2
    volumes:
      - /mnt/c/Users/Yang/Desktop/distributedHotstuff:/home/hotstuff/distributed
    user: "hotstuff"
    working_dir: /home/hotstuff/distributed
    networks:
      - HotStuff
    command: [ "./hotstuff", "-id", "1" ]

  node2:
    image: hotstuff:2
    volumes:
      - /mnt/c/Users/Yang/Desktop/distributedHotstuff:/home/hotstuff/distributed
    user: "hotstuff"
    working_dir: /home/hotstuff/distributed
    networks:
      - HotStuff
    command: [ "./hotstuff", "-id", "2" ]

  node3:
    image: hotstuff:2
    volumes:
      - /mnt/c/Users/Yang/Desktop/distributedHotstuff:/home/hotstuff/distributed
    user: "hotstuff"
    working_dir: /home/hotstuff/distributed
    networks:
      - HotStuff
    command: [ "./hotstuff", "-id", "3" ]

  node4:
    image: hotstuff:2
    volumes:
      - /mnt/c/Users/Yang/Desktop/distributedHotstuff:/home/hotstuff/distributed
    user: "hotstuff"
    working_dir: /home/hotstuff/distributed
    networks:
      - HotStuff
    command: [ "./hotstuff", "-id", "4" ]

  node5:
    image: hotstuff:2
    volumes:
      - /mnt/c/Users/Yang/Desktop/distributedHotstuff:/home/hotstuff/distributed
    user: "hotstuff"
    working_dir: /home/hotstuff/distributed
    networks:
      - HotStuff
    command: [ "./hotstuff", "-id", "5" ]

  node6:
    image: hotstuff:2
    volumes:
      - /mnt/c/Users/Yang/Desktop/distributedHotstuff:/home/hotstuff/distributed
    user: "hotstuff"
    working_dir: /home/hotstuff/distributed
    networks:
      - HotStuff
    command: [ "./hotstuff", "-id", "6" ]

  node7:
    image: hotstuff:2
    volumes:
      - /mnt/c/Users/Yang/Desktop/distributedHotstuff:/home/hotstuff/distributed
    user: "hotstuff"
    working_dir: /home/hotstuff/distributed
    networks:
      - HotStuff
    command: [ "./hotstuff", "-id", "7" ]

  node8:
    image: hotstuff:2
    volumes:
      - /mnt/c/Users/Yang/Desktop/distributedHotstuff:/home/hotstuff/distributed
    user: "hotstuff"
    working_dir: /home/hotstuff/distributed
    networks:
      - HotStuff
    command: [ "./hotstuff", "-id", "8" ]

  node9:
    image: hotstuff:2
    volumes:
      - /mnt/c/Users/Yang/Desktop/distributedHotstuff:/home/hotstuff/distributed
    user: "hotstuff"
    working_dir: /home/hotstuff/distributed
    networks:
      - HotStuff
    command: [ "./hotstuff", "-id", "9" ]

  node10:
    image: hotstuff:2
    volumes:
      - /mnt/c/Users/Yang/Desktop/distributedHotstuff:/home/hotstuff/distributed
    user: "hotstuff"
    working_dir: /home/hotstuff/distributed
    networks:
      - HotStuff
    command: [ "./hotstuff", "-id", "10" ]


networks:
  HotStuff:
    external: true
