// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.24.0
// source: hotstuff/proto/enums.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgType int32

const (
	MsgType_PREPARE         MsgType = 0
	MsgType_PRE_COMMIT      MsgType = 1
	MsgType_COMMIT          MsgType = 2
	MsgType_DECIDE          MsgType = 3
	MsgType_PREPARE_VOTE    MsgType = 4
	MsgType_PRE_COMMIT_VOTE MsgType = 5
	MsgType_COMMIT_VOTE     MsgType = 6
	MsgType_NEW_VIEW        MsgType = 7
	MsgType_TIME_OUT        MsgType = 8
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "PREPARE",
		1: "PRE_COMMIT",
		2: "COMMIT",
		3: "DECIDE",
		4: "PREPARE_VOTE",
		5: "PRE_COMMIT_VOTE",
		6: "COMMIT_VOTE",
		7: "NEW_VIEW",
		8: "TIME_OUT",
	}
	MsgType_value = map[string]int32{
		"PREPARE":         0,
		"PRE_COMMIT":      1,
		"COMMIT":          2,
		"DECIDE":          3,
		"PREPARE_VOTE":    4,
		"PRE_COMMIT_VOTE": 5,
		"COMMIT_VOTE":     6,
		"NEW_VIEW":        7,
		"TIME_OUT":        8,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_hotstuff_proto_enums_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_hotstuff_proto_enums_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_hotstuff_proto_enums_proto_rawDescGZIP(), []int{0}
}

var File_hotstuff_proto_enums_proto protoreflect.FileDescriptor

var file_hotstuff_proto_enums_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x2a, 0x92, 0x01, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07,
	0x50, 0x52, 0x45, 0x50, 0x41, 0x52, 0x45, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x52, 0x45,
	0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x49, 0x54, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x4f, 0x4d,
	0x4d, 0x49, 0x54, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x43, 0x49, 0x44, 0x45, 0x10,
	0x03, 0x12, 0x10, 0x0a, 0x0c, 0x50, 0x52, 0x45, 0x50, 0x41, 0x52, 0x45, 0x5f, 0x56, 0x4f, 0x54,
	0x45, 0x10, 0x04, 0x12, 0x13, 0x0a, 0x0f, 0x50, 0x52, 0x45, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x49,
	0x54, 0x5f, 0x56, 0x4f, 0x54, 0x45, 0x10, 0x05, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x4f, 0x4d, 0x4d,
	0x49, 0x54, 0x5f, 0x56, 0x4f, 0x54, 0x45, 0x10, 0x06, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x45, 0x57,
	0x5f, 0x56, 0x49, 0x45, 0x57, 0x10, 0x07, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x49, 0x4d, 0x45, 0x5f,
	0x4f, 0x55, 0x54, 0x10, 0x08, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hotstuff_proto_enums_proto_rawDescOnce sync.Once
	file_hotstuff_proto_enums_proto_rawDescData = file_hotstuff_proto_enums_proto_rawDesc
)

func file_hotstuff_proto_enums_proto_rawDescGZIP() []byte {
	file_hotstuff_proto_enums_proto_rawDescOnce.Do(func() {
		file_hotstuff_proto_enums_proto_rawDescData = protoimpl.X.CompressGZIP(file_hotstuff_proto_enums_proto_rawDescData)
	})
	return file_hotstuff_proto_enums_proto_rawDescData
}

var file_hotstuff_proto_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hotstuff_proto_enums_proto_goTypes = []interface{}{
	(MsgType)(0), // 0: pb.MsgType
}
var file_hotstuff_proto_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hotstuff_proto_enums_proto_init() }
func file_hotstuff_proto_enums_proto_init() {
	if File_hotstuff_proto_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hotstuff_proto_enums_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hotstuff_proto_enums_proto_goTypes,
		DependencyIndexes: file_hotstuff_proto_enums_proto_depIdxs,
		EnumInfos:         file_hotstuff_proto_enums_proto_enumTypes,
	}.Build()
	File_hotstuff_proto_enums_proto = out.File
	file_hotstuff_proto_enums_proto_rawDesc = nil
	file_hotstuff_proto_enums_proto_goTypes = nil
	file_hotstuff_proto_enums_proto_depIdxs = nil
}
